name: scrape

on:
    schedule:
        - cron: '0 * * * *'

    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12

            - name: Installing splinter
              run: |
                  echo Running 'pip install requests beautifulsoup4'
                  pip install requests beautifulsoup4

            - name: Run scraper
              run: |
                  echo Running 'python scrape.py'
                  python scrape.py
            - name: Git Commit/Push Changes
              uses: actions-x/commit@v6
