name: scrape

on:
    schedule:
        - cron: '0 0 * * *'

    workflow_dispatch:

jobs:
    scrape:
        needs: setup
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: run scraper
              run: |
                  echo Running 'python scrape.py'
                  python scrape.py

    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.12

            - name: Remove Chrome
              run: |
                  echo Running 'sudo apt purge google-chrome-stable'
                  sudo apt purge google-chrome-stable

            - name: Remove Chrome
              run: |
                  echo Running 'sudo apt purge chromium-browser'
                  sudo apt purge chromium-browser

            - name: Install Chrome
              run: |
                  echo Running 'sudo apt install -y chromium-browser'
                  sudo apt install -y chromium-browser

            - name: Installing splinter
              run: |
                  echo Running 'pip install splinter'
                  pip install splinter
