name: scrape

on:
    schedule:
        - cron: '0 * * * *'

    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Installing splinter
              run: |
                  echo Running 'pip install -r requirements.txt'
                  pip install -r requirements.txt

            - name: Run scraper
              run: |
                  echo Running 'python scrape.py'
                  python scrape.py

            - name: Upload to repository
              run: |
                  date > last_run.txt
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "GitHub Actions Update"
                  git push
